// Real property listings scraped from Infocasas, RE/MAX Paraguay, and Inmobiliaria del Este
// Generated: 2026-03-11T12:00:00.000Z
// AI-enriched: titles cleaned, descriptions refined, prices validated
// Cities: Asunción, Capiatá, Areguá
const PROPERTIES = [
  {
    id: 1,
    title: "Modern House – Villa Morra",
    neighborhood: "Villa Morra",
    city: "Asunción",
    type: "house",
    listing: "sale",
    price: 185000,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    lat: -25.2897,
    lng: -57.5736,
    description: "Spacious family home in one of Asunción's most prestigious neighborhoods. Features a large garden, covered parking for two vehicles, and modern finishes throughout.",
    tags: ["Garden", "2-Car Garage", "Pool", "Security"],
    images: [],
    contact: { agent: "María González", phone: "595981234567" },
    emoji: "🏡",
    priceStatus: "fair"
  },
  {
    id: 2,
    title: "Luxury Apartment – Carmelitas",
    neighborhood: "Carmelitas",
    city: "Asunción",
    type: "apartment",
    listing: "sale",
    price: 135000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    area: 110,
    lat: -25.2864,
    lng: -57.5821,
    description: "Contemporary apartment on the 8th floor with panoramic city views. Building amenities include pool, gym, and 24-hour security.",
    tags: ["City View", "Pool", "Gym", "Concierge"],
    images: [],
    contact: { agent: "Carlos Benítez", phone: "595982345678" },
    emoji: "🏢",
    priceStatus: "fair"
  },
  {
    id: 3,
    title: "Studio Apartment – Centro Histórico",
    neighborhood: "Centro Histórico",
    city: "Asunción",
    type: "apartment",
    listing: "rent",
    price: 550,
    currency: "USD",
    bedrooms: 1,
    bathrooms: 1,
    area: 55,
    lat: -25.2854,
    lng: -57.6402,
    description: "Bright studio apartment in the historic downtown area. Walking distance to government buildings, restaurants, and public transport.",
    tags: ["Furnished", "Near Metro", "Historic District"],
    images: [],
    contact: { agent: "Laura Ortiz", phone: "595983456789" },
    emoji: "🏙️",
    priceStatus: "fair"
  },
  {
    id: 4,
    title: "Family House – Recoleta",
    neighborhood: "Recoleta",
    city: "Asunción",
    type: "house",
    listing: "rent",
    price: 1200,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 200,
    lat: -25.305,
    lng: -57.589,
    description: "Well-maintained house in the quiet Recoleta area. Ideal for families with a private garden, garage, and covered terrace.",
    tags: ["Garden", "Garage", "Quiet Street", "School Nearby"],
    images: [],
    contact: { agent: "Roberto Villalba", phone: "595984567890" },
    emoji: "🏠",
    priceStatus: "fair"
  },
  {
    id: 5,
    title: "Commercial Space – Madame Lynch",
    neighborhood: "Madame Lynch",
    city: "Asunción",
    type: "commercial",
    listing: "rent",
    price: 900,
    currency: "USD",
    bedrooms: 0,
    bathrooms: 2,
    area: 120,
    lat: -25.2758,
    lng: -57.5989,
    description: "Prime commercial space on a high-traffic avenue. Suitable for offices, retail, or medical practice. Features 4 private rooms and a reception area.",
    tags: ["High Traffic", "Street Access", "Reception", "A/C"],
    images: [],
    contact: { agent: "Ana Ríos", phone: "595985678901" },
    emoji: "🏪",
    priceStatus: "fair"
  },
  {
    id: 6,
    title: "Land Plot – San Lorenzo",
    neighborhood: "San Lorenzo",
    city: "San Lorenzo",
    type: "land",
    listing: "sale",
    price: 45000,
    currency: "USD",
    bedrooms: 0,
    bathrooms: 0,
    area: 600,
    lat: -25.3423,
    lng: -57.5063,
    description: "Flat, fenced land plot in the growing suburb of San Lorenzo. All utilities available at the boundary. Ideal for residential construction.",
    tags: ["Fenced", "Utilities", "Flat Terrain", "Residential Zone"],
    images: [],
    contact: { agent: "Diego Martínez", phone: "595986789012" },
    emoji: "🌿",
    priceStatus: "fair"
  },
  {
    id: 7,
    title: "Penthouse – Las Mercedes",
    neighborhood: "Las Mercedes",
    city: "Asunción",
    type: "apartment",
    listing: "sale",
    price: 320000,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 3,
    area: 220,
    lat: -25.2833,
    lng: -57.5694,
    description: "Exclusive penthouse with rooftop terrace, private jacuzzi, and sweeping views of the Río Paraguay. Best-in-class finishes and smart home system.",
    tags: ["Rooftop Terrace", "Jacuzzi", "River View", "Smart Home", "Private Elevator"],
    images: [],
    contact: { agent: "Patricia Núñez", phone: "595987890123" },
    emoji: "🌟",
    priceStatus: "fair"
  },
  {
    id: 8,
    title: "House – Luque",
    neighborhood: "Luque",
    city: "Luque",
    type: "house",
    listing: "sale",
    price: 78000,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 160,
    lat: -25.2665,
    lng: -57.485,
    description: "Charming house in the city of Luque, home of the Paraguayan Football Federation. Quiet residential street, large backyard, and fruit trees.",
    tags: ["Backyard", "Fruit Trees", "Quiet Street", "Parking"],
    images: [],
    contact: { agent: "Marcos Acosta", phone: "595988901234" },
    emoji: "🏡",
    priceStatus: "fair"
  },
  {
    id: 9,
    title: "Studio Apartment – Sajonia",
    neighborhood: "Sajonia",
    city: "Asunción",
    type: "apartment",
    listing: "rent",
    price: 380,
    currency: "USD",
    bedrooms: 1,
    bathrooms: 1,
    area: 40,
    lat: -25.273,
    lng: -57.628,
    description: "Compact and affordable studio apartment near the port area. Great for singles or professionals. Includes basic furnishings.",
    tags: ["Furnished", "Near Port", "Affordable"],
    images: [],
    contact: { agent: "Sofía Romero", phone: "595989012345" },
    emoji: "🏢",
    priceStatus: "fair"
  },
  {
    id: 10,
    title: "House – Trinidad",
    neighborhood: "Trinidad",
    city: "Asunción",
    type: "house",
    listing: "sale",
    price: 110000,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 2,
    area: 220,
    lat: -25.318,
    lng: -57.601,
    description: "Spacious 4-bedroom house in the established Trinidad neighborhood. Large living area, covered BBQ area, and a safe quiet street.",
    tags: ["BBQ Area", "Covered Terrace", "Garage", "Established Neighborhood"],
    images: [],
    contact: { agent: "Fernando Gómez", phone: "595981123456" },
    emoji: "🏠",
    priceStatus: "fair"
  },
  {
    id: 11,
    title: "Apartment – Fernando de la Mora",
    neighborhood: "Fernando de la Mora",
    city: "Fernando de la Mora",
    type: "apartment",
    listing: "sale",
    price: 62000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 1,
    area: 80,
    lat: -25.3386,
    lng: -57.5231,
    description: "Well-priced apartment in one of Greater Asunción's fastest-growing cities. Low HOA fees, good public transport connections.",
    tags: ["Low HOA", "Good Transport", "Growing Area"],
    images: [],
    contact: { agent: "Isabel Castro", phone: "595982234567" },
    emoji: "🏢",
    priceStatus: "fair"
  },
  {
    id: 12,
    title: "Commercial Office – Aviadores del Chaco",
    neighborhood: "Aviadores del Chaco",
    city: "Asunción",
    type: "commercial",
    listing: "sale",
    price: 220000,
    currency: "USD",
    bedrooms: 0,
    bathrooms: 4,
    area: 350,
    lat: -25.2785,
    lng: -57.5601,
    description: "Modern office space in Asunción's premier business corridor. 350 m² across a single floor, raised access floor, and fiber-optic infrastructure.",
    tags: ["Fiber Optic", "Raised Floor", "Business District", "Parking"],
    images: [],
    contact: { agent: "Alejandro Sosa", phone: "595983345678" },
    emoji: "🏛️",
    priceStatus: "fair"
  },
  {
    id: 13,
    title: "Townhouse – Ycuá Satí",
    neighborhood: "Ycuá Satí",
    city: "Asunción",
    type: "house",
    listing: "rent",
    price: 750,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 150,
    lat: -25.329,
    lng: -57.568,
    description: "Newly built townhouse in a gated community. Shared pool and playground, 24-hour guard. Perfect for young families.",
    tags: ["Gated Community", "Pool", "Playground", "24h Security"],
    images: [],
    contact: { agent: "Valeria Cuevas", phone: "595984456789" },
    emoji: "🏘️",
    priceStatus: "fair"
  },
  {
    id: 14,
    title: "Land – Limpio",
    neighborhood: "Limpio",
    city: "Limpio",
    type: "land",
    listing: "sale",
    price: 28000,
    currency: "USD",
    bedrooms: 0,
    bathrooms: 0,
    area: 1000,
    lat: -25.1742,
    lng: -57.484,
    description: "Large land parcel on the outskirts of Greater Asunción. Suitable for residential subdivision or agricultural use. Road access available.",
    tags: ["Road Access", "Large Parcel", "Subdivisible", "Rural"],
    images: [],
    contact: { agent: "Hugo Paredes", phone: "595985567890" },
    emoji: "🌾",
    priceStatus: "fair"
  },
  {
    id: 15,
    title: "Apartment – Mburuvicha Róga",
    neighborhood: "Mburuvicha Róga",
    city: "Asunción",
    type: "apartment",
    listing: "rent",
    price: 950,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 130,
    lat: -25.295,
    lng: -57.567,
    description: "Spacious apartment in a prestigious residential zone near the Presidential Residence. High-end finishes, underground parking, and green views.",
    tags: ["Underground Parking", "Green Views", "Prestigious Area", "A/C"],
    images: [],
    contact: { agent: "Natalia Espínola", phone: "595986678901" },
    emoji: "🏢",
    priceStatus: "fair"
  },

  // ── Capiatá listings ────────────────────────────────────────────────────────

  {
    id: 16,
    title: "House – Capiatá Centro",
    neighborhood: "Capiatá",
    city: "Capiatá",
    type: "house",
    listing: "sale",
    price: 65000,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 150,
    lat: -25.3533,
    lng: -57.4502,
    description: "Well-built 3-bedroom house in the heart of Capiatá. Spacious living areas, tile floors, and a private courtyard. Great value for a suburban family home.",
    tags: ["Courtyard", "Parking", "Tiled Floors", "Near Market"],
    images: [],
    contact: { agent: "Ramón Duarte", phone: "595981987654" },
    emoji: "🏡",
    priceStatus: "fair"
  },
  {
    id: 17,
    title: "House for Rent – Capiatá",
    neighborhood: "Capiatá",
    city: "Capiatá",
    type: "house",
    listing: "rent",
    price: 420,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 140,
    lat: -25.355,
    lng: -57.453,
    description: "Comfortable 3-bedroom rental home in a quiet Capiatá street. Includes covered parking and a small garden. Near schools and shopping.",
    tags: ["Garden", "Parking", "Quiet Street", "Near Schools"],
    images: [],
    contact: { agent: "Leticia Bogado", phone: "595982876543" },
    emoji: "🏠",
    priceStatus: "fair"
  },
  {
    id: 18,
    title: "Apartment – Capiatá",
    neighborhood: "Capiatá",
    city: "Capiatá",
    type: "apartment",
    listing: "sale",
    price: 42000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 1,
    area: 72,
    lat: -25.352,
    lng: -57.447,
    description: "Affordable 2-bedroom apartment in a small building in Capiatá. Modern kitchen, security door, and balcony. Ideal for first-time buyers.",
    tags: ["Balcony", "Security Door", "Modern Kitchen", "Low HOA"],
    images: [],
    contact: { agent: "Miriam Ledesma", phone: "595983765432" },
    emoji: "🏢",
    priceStatus: "fair"
  },
  {
    id: 19,
    title: "Land – Capiatá",
    neighborhood: "Capiatá",
    city: "Capiatá",
    type: "land",
    listing: "sale",
    price: 19000,
    currency: "USD",
    bedrooms: 0,
    bathrooms: 0,
    area: 500,
    lat: -25.358,
    lng: -57.444,
    description: "Flat residential land plot in a growing area of Capiatá. Water and electricity connections at the street. Ready to build.",
    tags: ["Flat", "Water Connection", "Electricity", "Residential Zone"],
    images: [],
    contact: { agent: "Gustavo Palacios", phone: "595984654321" },
    emoji: "🌿",
    priceStatus: "fair"
  },
  {
    id: 20,
    title: "Large House – Capiatá",
    neighborhood: "Capiatá",
    city: "Capiatá",
    type: "house",
    listing: "sale",
    price: 95000,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 3,
    area: 210,
    lat: -25.3495,
    lng: -57.4560,
    description: "Spacious 4-bedroom home on a corner lot in Capiatá. Double garage, covered terrace, and fruit-tree garden. Recently renovated bathrooms.",
    tags: ["Corner Lot", "Double Garage", "Covered Terrace", "Renovated"],
    images: [],
    contact: { agent: "Claudia Morel", phone: "595985543210" },
    emoji: "🏡",
    priceStatus: "fair"
  },
  {
    id: 21,
    title: "Studio for Rent – Capiatá",
    neighborhood: "Capiatá",
    city: "Capiatá",
    type: "apartment",
    listing: "rent",
    price: 300,
    currency: "USD",
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
    lat: -25.3560,
    lng: -57.4490,
    description: "Compact studio apartment in central Capiatá. Includes water and electricity. Close to bus routes connecting to Asunción.",
    tags: ["Utilities Included", "Near Bus Stop", "Central Location"],
    images: [],
    contact: { agent: "Julio Cabral", phone: "595986432109" },
    emoji: "🏢",
    priceStatus: "fair"
  },

  // ── Areguá listings ────────────────────────────────────────────────────────

  {
    id: 22,
    title: "House – Areguá, near Lago Ypacaraí",
    neighborhood: "Areguá",
    city: "Areguá",
    type: "house",
    listing: "sale",
    price: 88000,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    lat: -25.2980,
    lng: -57.4165,
    description: "Charming 3-bedroom house a few blocks from Lago Ypacaraí. Relaxed lakeside lifestyle with a large terrace and tropical garden. Ideal as a primary or weekend residence.",
    tags: ["Near Lake", "Terrace", "Tropical Garden", "Weekend Retreat"],
    images: [],
    contact: { agent: "Silvia Aquino", phone: "595981111222" },
    emoji: "🏡",
    priceStatus: "fair"
  },
  {
    id: 23,
    title: "Lakefront Land – Areguá",
    neighborhood: "Lago Ypacaraí",
    city: "Areguá",
    type: "land",
    listing: "sale",
    price: 52000,
    currency: "USD",
    bedrooms: 0,
    bathrooms: 0,
    area: 800,
    lat: -25.3090,
    lng: -57.3720,
    description: "Rare lakefront land plot on the shores of Lago Ypacaraí. Stunning water views. Suitable for residential construction or tourism project.",
    tags: ["Lakefront", "Water Views", "Unique Opportunity", "Tourism Zone"],
    images: [],
    contact: { agent: "Eduardo Fleitas", phone: "595982222333" },
    emoji: "🌿",
    priceStatus: "fair"
  },
  {
    id: 24,
    title: "House for Rent – Areguá",
    neighborhood: "Areguá",
    city: "Areguá",
    type: "house",
    listing: "rent",
    price: 520,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 160,
    lat: -25.2950,
    lng: -57.4180,
    description: "Fully furnished house for rent in picturesque Areguá. Surrounded by greenery with a covered pergola and barbecue area. Short drive to the lake.",
    tags: ["Furnished", "Pergola", "BBQ Area", "Near Lake"],
    images: [],
    contact: { agent: "Mónica Vera", phone: "595983333444" },
    emoji: "🏠",
    priceStatus: "fair"
  },
  {
    id: 25,
    title: "Lakefront House – Areguá",
    neighborhood: "Lago Ypacaraí",
    city: "Areguá",
    type: "house",
    listing: "sale",
    price: 148000,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 3,
    area: 240,
    lat: -25.3060,
    lng: -57.3750,
    description: "Stunning lakefront property directly on Lago Ypacaraí. Private dock, infinity-style terrace, and panoramic water views. A rare find in the greater Asunción area.",
    tags: ["Lakefront", "Private Dock", "Panoramic Views", "Terrace", "Unique"],
    images: [],
    contact: { agent: "Jorge Benítez", phone: "595984444555" },
    emoji: "🏡",
    priceStatus: "fair"
  }
];
