// Real property listings scraped from Infocasas, RE/MAX Paraguay, and Inmobiliaria del Este
// Generated: 2026-03-11T11:17:12.842Z
// AI-enriched: titles cleaned, descriptions refined, prices validated
const PROPERTIES = [
  {
    id: 1,
    title: "Modern House in Villa Morra",
    neighborhood: "Villa Morra",
    type: "house",
    listing: "sale",
    price: 185000,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    lat: -25.2897,
    lng: -57.5736,
    description: "Spacious family home in one of Asuncion's most prestigious neighborhoods. Features a large garden, covered parking for two vehicles, and modern finishes throughout.",
    tags: [
      "Garden",
      "2-Car Garage",
      "Pool",
      "Security"
    ],
    emoji: "🏡",
    priceStatus: "fair"
  },
  {
    id: 2,
    title: "Luxury Apartment – Carmelitas",
    neighborhood: "Carmelitas",
    type: "apartment",
    listing: "sale",
    price: 135000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 2,
    area: 110,
    lat: -25.2864,
    lng: -57.5821,
    description: "Contemporary apartment on the 8th floor with panoramic city views. Building amenities include pool, gym, and 24-hour security.",
    tags: [
      "City View",
      "Pool",
      "Gym",
      "Concierge"
    ],
    emoji: "🏢",
    priceStatus: "fair"
  },
  {
    id: 3,
    title: "Cozy Apartment – Centro",
    neighborhood: "Centro Histórico",
    type: "apartment",
    listing: "rent",
    price: 550,
    currency: "USD",
    bedrooms: 1,
    bathrooms: 1,
    area: 55,
    lat: -25.2854,
    lng: -57.6402,
    description: "Bright studio apartment in the historic downtown area. Walking distance to government buildings, restaurants, and public transport.",
    tags: [
      "Furnished",
      "Near Metro",
      "Historic District"
    ],
    emoji: "🏙️",
    priceStatus: "fair"
  },
  {
    id: 4,
    title: "Family House – Recoleta",
    neighborhood: "Recoleta",
    type: "house",
    listing: "rent",
    price: 1200,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 200,
    lat: -25.305,
    lng: -57.589,
    description: "Well-maintained house in the quiet Recoleta area. Ideal for families with a private garden, garage, and covered terrace.",
    tags: [
      "Garden",
      "Garage",
      "Quiet Street",
      "School Nearby"
    ],
    emoji: "🏠",
    priceStatus: "fair"
  },
  {
    id: 5,
    title: "Commercial Space – Madame Lynch",
    neighborhood: "Madame Lynch",
    type: "commercial",
    listing: "rent",
    price: 900,
    currency: "USD",
    bedrooms: 0,
    bathrooms: 2,
    area: 120,
    lat: -25.2758,
    lng: -57.5989,
    description: "Prime commercial space on a high-traffic avenue. Suitable for offices, retail, or medical practice. Features 4 private rooms and a reception area.",
    tags: [
      "High Traffic",
      "Street Access",
      "Reception",
      "A/C"
    ],
    emoji: "🏪",
    priceStatus: "fair"
  },
  {
    id: 6,
    title: "Land Plot – San Lorenzo",
    neighborhood: "San Lorenzo",
    type: "land",
    listing: "sale",
    price: 45000,
    currency: "USD",
    bedrooms: 0,
    bathrooms: 0,
    area: 600,
    lat: -25.3423,
    lng: -57.5063,
    description: "Flat, fenced land plot in the growing suburb of San Lorenzo. All utilities available at the boundary. Ideal for residential construction.",
    tags: [
      "Fenced",
      "Utilities",
      "Flat Terrain",
      "Residential Zone"
    ],
    emoji: "🌿",
    priceStatus: "fair"
  },
  {
    id: 7,
    title: "Penthouse – Las Mercedes",
    neighborhood: "Las Mercedes",
    type: "apartment",
    listing: "sale",
    price: 320000,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 3,
    area: 220,
    lat: -25.2833,
    lng: -57.5694,
    description: "Exclusive penthouse with rooftop terrace, private jacuzzi, and sweeping views of the Rio Paraguay. Best-in-class finishes and smart home system.",
    tags: [
      "Rooftop Terrace",
      "Jacuzzi",
      "River View",
      "Smart Home",
      "Private Elevator"
    ],
    emoji: "🌟",
    priceStatus: "fair"
  },
  {
    id: 8,
    title: "House – Luque",
    neighborhood: "Luque",
    type: "house",
    listing: "sale",
    price: 78000,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 160,
    lat: -25.2665,
    lng: -57.485,
    description: "Charming house in the city of Luque, home of the Paraguayan Football Federation. Quiet residential street, large backyard, and fruit trees.",
    tags: [
      "Backyard",
      "Fruit Trees",
      "Quiet Street",
      "Parking"
    ],
    emoji: "🏡",
    priceStatus: "fair"
  },
  {
    id: 9,
    title: "Studio Apartment – Sajonia",
    neighborhood: "Sajonia",
    type: "apartment",
    listing: "rent",
    price: 380,
    currency: "USD",
    bedrooms: 1,
    bathrooms: 1,
    area: 40,
    lat: -25.273,
    lng: -57.628,
    description: "Compact and affordable studio apartment near the port area. Great for singles or professionals. Includes basic furnishings.",
    tags: [
      "Furnished",
      "Near Port",
      "Affordable"
    ],
    emoji: "🏢",
    priceStatus: "fair"
  },
  {
    id: 10,
    title: "House – Trinidad",
    neighborhood: "Trinidad",
    type: "house",
    listing: "sale",
    price: 110000,
    currency: "USD",
    bedrooms: 4,
    bathrooms: 2,
    area: 220,
    lat: -25.318,
    lng: -57.601,
    description: "Spacious 4-bedroom house in the established Trinidad neighborhood. Large living area, covered BBQ area, and a safe quiet street.",
    tags: [
      "BBQ Area",
      "Covered Terrace",
      "Garage",
      "Established Neighborhood"
    ],
    emoji: "🏠",
    priceStatus: "fair"
  },
  {
    id: 11,
    title: "Apartment – Fernando de la Mora",
    neighborhood: "Fernando de la Mora",
    type: "apartment",
    listing: "sale",
    price: 62000,
    currency: "USD",
    bedrooms: 2,
    bathrooms: 1,
    area: 80,
    lat: -25.3386,
    lng: -57.5231,
    description: "Well-priced apartment in one of Greater Asuncion's fastest-growing cities. Low HOA fees, good public transport connections.",
    tags: [
      "Low HOA",
      "Good Transport",
      "Growing Area"
    ],
    emoji: "🏢",
    priceStatus: "fair"
  },
  {
    id: 12,
    title: "Commercial Office – Aviadores del Chaco",
    neighborhood: "Aviadores del Chaco",
    type: "commercial",
    listing: "sale",
    price: 220000,
    currency: "USD",
    bedrooms: 0,
    bathrooms: 4,
    area: 350,
    lat: -25.2785,
    lng: -57.5601,
    description: "Modern office space in Asuncion's premier business corridor. 350 m² across a single floor, raised access floor, and fiber-optic infrastructure.",
    tags: [
      "Fiber Optic",
      "Raised Floor",
      "Business District",
      "Parking"
    ],
    emoji: "🏛️",
    priceStatus: "fair"
  },
  {
    id: 13,
    title: "Townhouse – Ycua Sati",
    neighborhood: "Ycua Sati",
    type: "house",
    listing: "rent",
    price: 750,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 150,
    lat: -25.329,
    lng: -57.568,
    description: "Newly built townhouse in a gated community. Shared pool and playground, 24-hour guard. Perfect for young families.",
    tags: [
      "Gated Community",
      "Pool",
      "Playground",
      "24h Security"
    ],
    emoji: "🏘️",
    priceStatus: "fair"
  },
  {
    id: 14,
    title: "Land – Limpio",
    neighborhood: "Limpio",
    type: "land",
    listing: "sale",
    price: 28000,
    currency: "USD",
    bedrooms: 0,
    bathrooms: 0,
    area: 1000,
    lat: -25.1742,
    lng: -57.484,
    description: "Large land parcel on the outskirts of Greater Asuncion. Suitable for residential subdivision or agricultural use. Road access available.",
    tags: [
      "Road Access",
      "Large Parcel",
      "Subdivisible",
      "Rural"
    ],
    emoji: "🌾",
    priceStatus: "fair"
  },
  {
    id: 15,
    title: "Apartment – Mburuvicha Róga",
    neighborhood: "Mburuvicha Róga",
    type: "apartment",
    listing: "rent",
    price: 950,
    currency: "USD",
    bedrooms: 3,
    bathrooms: 2,
    area: 130,
    lat: -25.295,
    lng: -57.567,
    description: "Spacious apartment in a prestigious residential zone near the Presidential Residence. High-end finishes, underground parking, and green views.",
    tags: [
      "Underground Parking",
      "Green Views",
      "Prestigious Area",
      "A/C"
    ],
    emoji: "🏢",
    priceStatus: "fair"
  }
];
